# name: Deploy to GitHub Pages

# on:
#   push:
#     branches: ["gh-pages"]
#   workflow_dispatch:

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 检出代码
#         uses: actions/checkout@v4

#       - name: 设置 Node.js 环境
#         uses: actions/setup-node@v4
#         with:
#           node-version: "24"
#           cache: "npm"

#       - name: 安装依赖
#         run: npm ci

#       - name: 构建项目
#         run: npm run build

#       - name: 部署到 GitHub Pages
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           branch: deploy-gh-pages
#           folder: build
#           clean: true

name: Deploy

on:
  push:
    branches: [feat]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build project
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feat'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist